clone_folder: "C:\msys64\home\ghc\shake-build"

install:
    - set MSYSTEM=MINGW64
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;%PATH%
    - bash -lc "pacman -S --noconfirm git binutils p7zip gcc"
    - bash -lc "curl -LsS http://www.haskell.org/ghc/dist/7.10.1/ghc-7.10.1-x86_64-unknown-mingw32.tar.xz | tar -xJ -C /mingw64 --strip-components=1"
    - bash -lc "mkdir /usr/local"
    - bash -lc "mkdir /usr/local/bin"
    - bash -lc "curl -LsS https://www.haskell.org/cabal/release/cabal-install-1.22.0.0/cabal-1.22.0.0-i386-unknown-mingw32.tar.gz | tar -xz -C /usr/local/bin"
    - bash -lc "cabal update"
    - bash -lc "cabal install -j --prefix=/usr/local alex happy"

build_script:
    - echo "test"

test: off
