clone_folder: "C:\\msys64\\home\\ghc\\shake-build"

install:
    - cd
    - set MSYSTEM=MINGW64
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;%PATH%
    - set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\local\bin\;%APPVEYOR_BUILD_FOLDER%
    - curl -ostack.zip -LsS --insecure https://www.stackage.org/stack/windows-x86_64
    - 7z x stack.zip stack.exe
    - bash -lc "curl -LsS http://www.haskell.org/ghc/dist/7.10.3/ghc-7.10.3-x86_64-unknown-mingw32.tar.xz | tar -xJ -C /mingw64 --strip-components=1"
    - stack exec -- pacman -S --noconfirm perl gcc binutils p7zip git
    - echo "" | stack --no-terminal install alex happy shake ansi-terminal mtl
    - git clone --recursive git://git.haskell.org/ghc.git C:\msys64\home\ghc\tmp
    - bash -lc "mv /home/ghc/tmp/* /home/ghc"
    - cd C:\msys64\home\ghc
    - stack exec -- perl boot
    - stack exec -- configure --enable-tarballs-autodownload
    - ghc   --version
    - stack --version
    - alex  --version
    - happy --version

build_script:
    - cd
    - bash -lc "./shake-build/build.bat -j --no-progress"
