clone_folder: "C:\\msys64\\home\\ghc\\shake-build"

install:
    - set MSYSTEM=MINGW64
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;%PATH%
    - curl -ostack.zip -LsS --insecure https://www.stackage.org/stack/windows-x86_64
    - 7z x stack.zip stack.exe
    - bash -lc "curl -LsS http://www.haskell.org/ghc/dist/7.10.3/ghc-7.10.3-x86_64-unknown-mingw32.tar.xz | tar -xJ -C /mingw64 --strip-components=1"
    - stack exec -- pacman -S --noconfirm gcc binutils p7zip git
    - echo "" | stack --no-terminal alex happy shake ansi-terminal mtl
    - set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\local\bin\
    - git clone --recursive git://git.haskell.org/ghc.git C:\msys64\home\ghc\tmp
    - bash -lc "mv /home/ghc/tmp/* /home/ghc"

build_script:
    - bash -lc "cd /home/ghc && ./boot"
    - bash -lc "cd /home/ghc && ./configure --enable-tarballs-autodownload"
    - bash -lc "cd /home/ghc && ./shake-build/build.bat -j --no-progress"
